# Generated by Django 5.2 on 2025-04-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_model_cnt_likes_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='cnt_likes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cnt_downloads',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество загрузок'),
        ),
    ]
