# Generated by Django 5.2 on 2025-04-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_model_cnt_likes_alter_model_cnt_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='cnt_likes',
        ),
    ]
